<?xml version="1.0" encoding="UTF-8"?>
<!-- You may freely edit this file. See commented blocks below for -->
<!-- some examples of how to customize the build. -->
<!-- (If you delete it and reopen the project it will be recreated.) -->
<!-- By default, only the Clean and Build commands use this build script. -->
<!-- Commands such as Run, Debug, and Test only use this build script if -->
<!-- the Compile on Save feature is turned off for the project. -->
<!-- You can turn off the Compile on Save (or Deploy on Save) setting -->
<!-- in the project's Project Properties dialog box.-->
<project name="BiblioRepo" default="default" basedir=".">
    <description>Builds, tests, and runs the project BiblioRepo.</description>
    <import file="nbproject/build-impl.xml"/>
    <!--

    There exist several targets which are by default empty and which can be 
    used for execution of your tasks. These targets are usually executed 
    before and after some main targets. They are: 

      -pre-init:                 called before initialization of project properties
      -post-init:                called after initialization of project properties
      -pre-compile:              called before javac compilation
      -post-compile:             called after javac compilation
      -pre-compile-single:       called before javac compilation of single file
      -post-compile-single:      called after javac compilation of single file
      -pre-compile-test:         called before javac compilation of JUnit tests
      -post-compile-test:        called after javac compilation of JUnit tests
      -pre-compile-test-single:  called before javac compilation of single file
      -post-compile-test-single: called after javac compilation of single file
      -pre-jar:                  called before JAR building
      -post-jar:                 called after JAR building
      -post-clean:               called after cleaning build products

    (Targets beginning with '-' are not intended to be called on their own.)

    Example of inserting an obfuscator after compilation could look like this:

        <target name="-post-compile">
            <obfuscate>
                <fileset dir="${build.classes.dir}"/>
            </obfuscate>
        </target>

    For list of available properties check the imported 
    nbproject/build-impl.xml file. 

    Another way to customize the build is by overriding existing main targets.
    The overriding target will be called instead of the imported target.

    The overriding target should be placed in the main build file.

    For example to override the target for building a JAR file (the main target
    for this type of project) you can use:

        <target name="jar" depends="BiblioRepo-init">
            <echo message="Building JAR file"/>
            <jar jarfile="${dist.jar}" includes="**/*.class">
                <fileset dir="${build.classes.dir}"/>
                <fileset dir="${src.dir}" excludes="**/*.java"/>
            </jar>
        </target>

    You can also use properties defined in the imported file. These properties 
    are considered private and can be overridden only if make sense.

    Example of overriding the target for testing:

        <target name="test" depends="BiblioRepo-init">
            <junit haltonfailure="true" fork="true">
                <formatter type="brief" usefile="false"/>
                <test name="${test.class}"/>
                <classpath>
                    <path path="${run.test.classpath}"/>
                </classpath>
            </junit>
        </target>

    Notice that overriding properties like ${src.dir} is not advised. You can
    override ant properties defined in the nbproject/project.properties file instead.
    -->
    <!-- Agregar propiedad para AbsoluteLayout.jar -->
    <property name="libs.AbsoluteLayout.classpath" value="lib/AbsoluteLayout.jar"/>
</project>